name: CI Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_ARN: ${{ secrets.AWS_ARN }}
  TF_VAR_AWS_ARN: ${{ secrets.AWS_ARN }}
  TF_VAR_REPO: ${{ secrets.REPO }}
  TF_VAR_IP: ${{ secrets.IP }}

jobs:
  terraform-init:
    name: Terraform init
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/root

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ARN }}:role/AwsAssumeTFPolicy
          aws-region: eu-west-1

      - name: Run tf init
        run: terraform init

      - name: Create terraform cache
        uses: actions/cache/save@v4
        with:
          path: terraform
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}

  terraform-check:
    name: Terraform check
    runs-on: ubuntu-latest
    needs: terraform-init
    defaults:
      run:
        shell: bash
        working-directory: terraform/root

    steps:
      - uses: actions/checkout@v4

      - name: Restore terraform cache
        uses: actions/cache/restore@v4
        with:
          path: terraform
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Run tf check
        run: terraform fmt

  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    needs: terraform-check
    defaults:
      run:
        shell: bash
        working-directory: terraform/root

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ARN }}:role/AwsAssumeTFPolicy
          aws-region: eu-west-1

      - name: Restore terraform cache
        uses: actions/cache/restore@v4
        with:
          path: terraform
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Run tf plan
        run: terraform plan

  terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    defaults:
      run:
        shell: bash
        working-directory: terraform/root

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ARN }}:role/AwsAssumeTFPolicy
          aws-region: eu-west-1

      - name: Restore terraform cache
        uses: actions/cache/restore@v4
        with:
          path: terraform
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Run tf apply
        run: terraform apply -auto-approve
